# Generated by Django 5.2.8 on 2025-12-26 05:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на новость')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя преподавателя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Стоимость')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Длительность занятия (минуты)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('instructors', models.ManyToManyField(related_name='courses', to='courses.instructor', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Саббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('time_slot', models.CharField(choices=[('8-10', '8:00-10:00'), ('10-12', '10:00-12:00'), ('12-14', '12:00-14:00'), ('14-16', '14:00-16:00'), ('16-18', '16:00-18:00'), ('18-20', '18:00-20:00'), ('20-22', '20:00-22:00')], max_length=5, verbose_name='Время')),
                ('max_seats', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество мест')),
                ('booked_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Занято мест')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Кабинет/зал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Ячейка расписания',
                'verbose_name_plural': 'Ячейки расписания',
                'ordering': ['day_of_week', 'time_slot'],
                'unique_together': {('course', 'day_of_week', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Имя студента')),
                ('student_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('student_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('student_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Рассмотрена')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('data_consent', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрено пользователем')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('time_slots', models.ManyToManyField(related_name='enrollments', to='courses.timeslot', verbose_name='Выбранные ячейки расписания')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('email_confirmation_token', models.CharField(blank=True, default='', max_length=100, verbose_name='Токен подтверждения email')),
                ('email_confirmation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
